GET https://api.zenmoney.ru/oauth2/authorize/?client_id={{client_id}}&redirect_uri=http://localhost:3000&response_type=code HTTP/1.1

####
POST https://api.zenmoney.ru/oauth2/authorize HTTP/1.1
Content-Type: application/json

{
  "authType": "password",
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
    var url = response.body.url
    var start = url.indexOf("?code=") + 6
    var end = url.indexOf("&user_id=")
    var auth_code = url.substring(start, end)
    client.global.set("auth_code", auth_code);
    // start = url.indexOf("&user_id=") + 9
    // end = url.indexOf("&regist")
    // var user_id = url.substring(start, end)
    // client.global.set("user_id", user_id);
    %}


###
POST https://api.zenmoney.ru/oauth2/token/ HTTP/1.1
Host: api.zenmoney.ru
Content-Type: application/x-www-form-urlencoded

{
  "client_id": "{{client_id}}",
  "client_secret": "{{client_secret}}",
  "redirect_uri": "http://localhost:3000",
  "code": "{{auth_code}}",
  "grant_type": "authorization_code"
}

