###
GET https://api.zenmoney.ru/oauth2/authorize/?client_id=g61164be3dd7521a6511ce97adc6bb&redirect_uri=http://localhost:3000&response_type=code

> {%
client.global.set("cookie", response.headers.valueOf('Set-Cookie'));
%}

###
POST https://api.zenmoney.ru/oauth2/authorize/
Content-Type: application/json
Cookie: {{cookie}}

{
  "authType": "password",
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
    var url = response.body.url
    var start = url.indexOf("?code=") + 6
    var end = url.indexOf("&user_id=")
    var auth_code = url.substring(start, end)
    client.global.set("auth_code", auth_code);
    // start = url.indexOf("&user_id=") + 9
    // end = url.indexOf("&regist")
    // var user_id = url.substring(start, end)
    // client.global.set("user_id", user_id);
    %}


###
POST https://api.zenmoney.ru/oauth2/token/
Content-Type: application/json

{
  "client_id": "g61164be3dd7521a6511ce97adc6bb",
  "client_secret": "b2828c65b7",
  "redirect_uri": "http://localhost:3000",
  "code": "{{auth_code}}",
  "grant_type": "authorization_code"
}
